import React, { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import CreateDoc from '../components/Create/CreateDoc'
import LoginVerify from '../components/LoginVerify/LoginVerify'

const admin = () => {
    const [ loggedIn, setLoggedIn] = useState(false)
  return (
    <div>
    <Head>
      <title>Admin</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className='px-[5%] md:px-[20%] bg-slate-100'>
      {/* ==== All posts */}
      {
        loggedIn ?  <CreateDoc /> : <LoginVerify setLoggedIn={setLoggedIn} />
      }
       
    </main>
  </div>
  )
}

export default admin