import React, { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import CreateDoc from '../components/Create/CreateDoc'

const admin = () => {
    const [user, setUser] = useState({
        name: 'price',
        pass: '123546'
    })
  return (
    <div>
    <Head>
      <title>Admin</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className='px-[5%] md:px-[20%] bg-slate-100'>
      {/* ==== All posts */}
        <CreateDoc />
    </main>
  </div>
  )
}

export default admin