import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'


export default function Home() {

  const [data, setData] = useState()
  useEffect(()=>{
    fetch('http://localhost:3001/')
    .then(res => res.json())
    .then(data => setData(data))
  },[])

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {
          data ? <h1>{data[0].name}</h1> : <h1>nai</h1>
        }
        <h1>Hello</h1>
    
      </main>
    </div>
  )
}
